### PR TITLE
change weights to to ints

### PR DESCRIPTION
**Pull request by michelleN**
This fixes some immediate issues @lachie83 pointed out but we still need a section describing weights and how they are calculated. https://github.com/deislabs/smi-spec/issues/63

### CODE REVIEW

**Comment by michelleN** [comment]
depends on #64

**Comment by abonas** [comment]
@michelleN is this partially addressing #45 ?

**Comment by michelleN** [comment]
@abonas yes and I also added issue #63 to help address the rest of it

**Comment by michelleN** [comment]
resolves #65

**Pull request merged**
